### ISSUE TITLE
Tutorial Instalasi Django pada Cloud Hosting

### ISSUE THREAD

**Issue by danangponorogo** [surabaya-py/talks#10]
*   Nama Lengkap: Danang Dismantoro, S.Kom
*   Pekerjaan:  ASN di Pemda Kab. Ponorogo / Mahasiswa S2 Telematika di ITS Surabaya (Cuti Tugas Belajar) / Full Stack Developer di https://fahiltek.co.id
*   Kontak yang bisa dihubungi (Email/Telegram): danang.dandies@gmail.com / 0811 8111 426
*   Judul Lightning Talks: Tutorial Instalasi Django pada Cloud Hosting
*   Overview (140 characters): Django adalah web framework dalam bahasa pemrograman Python yang menggunakan arsitektur MTV (Model - Template - View) = MVC (Model - View - Controller) di CI, kami akan sampaikan tutorial singkat instalasi Django pada Cloud Hosting, sehingga aplikasi Django kita dapat online di Web.
*   Brief Outline: 
    1.  Overview
    2.  Hosting yang support Python
    3.  Instalasi Django pada Cloud Hosting
    4.  Diskusi

**Comment by tegarimansyah** [comment]
Halo @danangponorogo 

Thank you sudah tertarik berkontribusi sebagai speaker lighning talk surabayapy. Untuk materi yang dibawakan apakah nanti membahas sampai MTV nya atau hanya deploy ke cloud hosting ya? Takutnya kalau pembahasal MTV bakal tidak cukup 5 menit.

Anyway, hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.

**Comment by danangponorogo** [comment]
Yg dibahas fleksibel menyesuaikan waktu. Kalo 5 menit barang Kali cukup
install django di cloud hosting sampai bisa diakses online gitu aja mungkin
Pada tanggal 17 Mei 2019 12.55, "Tegar Imansyah" <notifications@github.com>
menulis:

**Comment by tegarimansyah** [comment]
Oke siap. Karena kemungkinan akan demo online, untuk menghindari jika nanti ada masalah pada internet, mungkin bisa dikasih backup plan berupa screenshot. Untuk screenshot code yang bagus, nanti bisa di lihat di guide nya ya.

**Comment by danangponorogo** [comment]
Ok mas siap
Pada tanggal 17 Mei 2019 13.31, "Tegar Imansyah" <notifications@github.com>
menulis:

**Comment by danangponorogo** [comment]
mas surat undangan dan speaker guide ngirimnya kapan ?

**Comment by tegarimansyah** [comment]
Kira kira malam

**Comment by danangponorogo** [comment]
Ok makasih
