### ISSUE TITLE
Introduction to Test Driven Development using Flask 

### ISSUE THREAD

**Issue by kelvindesman** [surabaya-py/talks#11]
*   Nama Lengkap: Kelvin Desman
*   Pekerjaan:  Software Engineer (Back End) - Modana
*   Kontak yang bisa dihubungi (Email/Telegram): https://t.me/kelvindsmn
*   Judul Lightning Talks: Introduction to Test Driven Development using Flask 
*   Overview: TDD merupakan salah satu metodologi pengembangan software yang populer saat ini bersama dengan konsep _scrum_  dalam sebuah organisasi. TDD mengubah sebuah _entrypoint pengembangan _software dari sebuah _Unit Test_ dibandingkan _requirements pada metodologi tradisional. Dengan___ mempraktikan TDD kita dapat membuat kode kita berani dan tidak takut perubahan karena setiap perubahan dapat diuji terutama jika _codebase._ mulai menjadi besar. Jika kita ingin membuat sebuah kode yang _solid_ dan _robust_ terutama di environment _production_ Test Driven Development adalah salah satu solusinya.  
*   Brief Outline: 
    1.  Test Driven Development Overview
    2.  How it Works
    3.  How to Start
    4. TDD vs Traditional Development
    5. Conclussion

**Comment by tegarimansyah** [comment]
Halo @vousmeevoyez

Thank you sudah tertarik berkontribusi sebagai speaker lighning talk surabayapy. Materinya menarik banget. Tapi karena untuk besok hanya 5 menit, mungkin nanti bisa diatur materinya supaya tidak terpotong di tengah pembahasan. Bisa juga nih kedepan di upgrade jadi full talks hehe.

Ohh iya, hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.

**Comment by gallanpw** [comment]
Halo @vousmeevoyez 

Materi nya mantep ini, bisa buat tambahan ilmu
