### ISSUE TITLE
Bugless code with statically typed python code

### ISSUE THREAD

**Issue by famasya** [surabaya-py/talks#12]
*   Nama Lengkap: Abid Famasya
*   Pekerjaan:  CTO Trust Medis
*   Kontak yang bisa dihubungi (Telegram): http://t.me/famasya
*   Judul Lightning Talks: Bugless code with statically typed python code
*   Overview:  
Dalam development, terkadang kode memiliki bugs tersembunyi yang hanya dapat terdeteksi ketika kode telah _running_. Penyebabnya bisa jadi karena ketidaksesuaian _data types_ yang diproses oleh kode. Untuk mencegahnya kita bisa menggunakan static type checking untuk mencegah bugs bahkan ketika kode belum dijalankan.
*   Brief Outline: 
    1. Introduction to type checking
    2. Introduction to statically type checking
    3. Demo
    4. Conclusion

**Comment by tegarimansyah** [comment]
Halo @famasya 

Thank you sudah tertarik berkontribusi sebagai speaker lighning talk surabayapy. Materinya menarik banget. Tapi karena untuk besok hanya 5 menit, mungkin nanti bisa diatur materinya supaya tidak terpotong di tengah pembahasan. Bisa juga nih kedepan di upgrade jadi full talks hehe.

Ohh iya, hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.
