### ISSUE TITLE
Introduction : Python in odoo ERP

### ISSUE THREAD

**Issue by EdyKend** [surabaya-py/talks#13]
*   Nama Lengkap: Edy
*   Pekerjaan:  CEO
*   Kontak yang bisa dihubungi (Email/Telegram): edy@edaptec.com 
*   Judul Lightning Talks: Introduction : Python in odoo ERP
*   Overview (140 characters): 
    With 10.000+ apps in, Odoo covers all your business needs in a one-stop solution: no more interfaces between different software required. Odoo apps are perfectly integrated to each other, allowing you to fully automate your business processes.
*   Brief Outline: 
    1.  Overview odoo
    2.  Easy create app in odoo with python code
    3. Conclusion : No more painful for build a business solution.

**Comment by tegarimansyah** [comment]
Halo @EdyKend 

Thank you sudah tertarik berkontribusi sebagai speaker lighning talk surabayapy. Materinya menarik banget. Secara outline dan overview sudah sangat memungkinkan untuk dibawakan 5 menit. Sampai jumpa di meetup.

Ohh iya, hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.

**Comment by suryakencana007** [comment]
mantab ini yang selalu ditunggu2 materi dari Pak edy @EdyKend 👍
