### ISSUE TITLE
Scraping Data from Facebook with Python

### ISSUE THREAD

**Issue by oktavianidewi** [surabaya-py/talks#14]
*   Nama Lengkap: Dewi Oktaviani
*   Pekerjaan: Software Engineer
*   Kontak yang bisa dihubungi (Email/Telegram): oktaviani.dewi@gmail.com / @oktavianidewi
*   Judul Lightning Talks: Scraping Data from Facebook with Python
*   Overview (140 characters): *Scraping* adalah sebuah teknik untuk mendapatkan *unstructured data* di Facebook (tanpa Graph-API) dan mengonversi data tersebut menjadi *structured data* yang lebih *machine readable* dan siap untuk dianalisis lebih lanjut. Teknik *scrapping* ini penting untuk dipahami karena merupakan salah satu *skill-set* yang selayaknya dimiliki bagi yang ingin mendalami *Data Science*.

*   Brief Outline:
   1. Why scraping data?
   2. How to scrap data?
   3. Scraping Demo
   4. Result

**Comment by tegarimansyah** [comment]
Halo @oktavianidewi 

Thank you sudah tertarik berkontribusi sebagai speaker lighning talk surabayapy. Materinya menarik banget. Tapi karena untuk besok hanya 5 menit, mungkin nanti bisa diatur materinya, terutama pada saat demo, supaya tidak terpotong di tengah pembahasan. Bisa juga nih kedepan di upgrade jadi full talks hehe.

Ohh iya, hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.
