### ISSUE TITLE
OpenCV and myRIO communication using ROS

### ISSUE THREAD

**Issue by januarkai** [surabaya-py/talks#15]
*   Nama Lengkap: Januar Kailani Suaeb
*   Pekerjaan:  mahasiswa
*   Kontak yang bisa dihubungi (Email/Telegram): januarks14@gmail.com/januarks14
*   Judul Lightning Talks: OpenCV and myRio Communication using ROS
*   Overview (140 Characters): Computer vision bisa digunakan dalam berbagai hal. OpenCV biasa digunakan untuk langkah awal belajar computer vision. Sebagai awal pembelajaran, data visual dari OpenCV dapat dibenamkan pada kontroler sebagai contoh untuk menggerakkan aktuator. Maka agar komunikasi yang dilakukan bisa secara realtime digunakanlah ROS sebagai media komunikasi dari OpenCV ke myRIO untuk mengontrol aktuator.
*   Brief Outline: 
    1.  Pengenalan OpenCV, ROS and myRIO
    2.  Perancangan komunikasi anatara OpenCV dan myRIO menggunakan ROS
    3.  masalah - masalah yang sering terjadi saat menggunakan ROS di myRIO

**Comment by ridhof** [comment]
Hai @januarks14 
Perkenalkan, saya Ridho dari Surabaya.py
Sebelumnya kami ucapkan terima kasih atas antusiasme-nya dalam berkontribusi di Surabaya.py dengan mengisi Lightning Talks. 

Anyway, topik yang dibawakan sangat menarik, karena belum banyak yang mengisi talk dengan topik penggunaan Computer Vision dalam ROS.

Sebelumnya, kami informasikan bahwa Brief Outline digunakan untuk mengetahui poin-poin apa saja yang akan dibahas pada saat talks. Oleh karena itu, Brief Outline sangat berguna untuk mengetahui apakah topik talk sudah sesuai dengan apa yang teman-teman cari atau belum. Pastikan bahwa Brief Outline sudah sesuai dengan topik dan overview yang telah dituliskan ya!

Lightning talks memberikan kesempatan bagi para pembicara untuk berbagi ilmu hanya dalam waktu kurang lebih 5 menit. Lebih dari itu panitia akan memberitau jika waktunya sudah habis. Oleh karena itu, pastikan bahwa waktu talk kamu tidak melebihi waktu yang telah disediakan oleh panitia. Dan untuk menghindari masalah teknis, lebih baik gunakan screenshot pada potongan kode dan potongan program. Perlu guide untuk membuat slide yang bagus dalam menampilkan potongan kode dan program? Semoga guide [Codeware](https://github.com/surabaya-py/talks/blob/master/Lightning%20Talks%20README.md#good-references-on-presenting-code) ini bisa membantu kamu ya!

Tunggu informasi selanjutnya dari kami ya!
Terima kasih~
