### ISSUE TITLE
How to Prepare Your first PyCon Talk

### ISSUE THREAD

**Issue by rubiagatra** [surabaya-py/talks#17]
*   Nama Lengkap: Doni Rubiagatra
*   Pekerjaan:  Software Engineer (@kumparan)
*   Kontak yang bisa dihubungi (Email/Telegram): @rubiagatra 
*   Judul Talks: How to Prepare Your first PyCon Talk
*   Overview (140 characters): 
Menjadi seorang pembicara di PyCon merupakan pengalaman yang tak terlupakan. Namun untuk mempersiapkan sebuah talk ada yang harus diperhatikan apalagi jika kita baru pertama kali mendaftar. Kali ini saya akan berbagi pengalaman menjadi seorang speaker di PyCon dan mengajak teman - teman untuk membuat perjalanan "Public Speaking" sendiri.
*   Brief Outline: 
    1.  Pengalaman menjadi speaker di beberapa PyCon Asia
    2.  Menghadapi rasa takut untuk "Public Speaking"
    3.  Rencanakan Talk dan waktu sebelum talk
    4. Buat proposal dan dapatkan feedbback
    5. Tipe talk yang kemungkinan di "Reject"
    6. Pre-recording demo untuk menghindari masalah demo secara live
    7. Kenapa kamu harus mencoba "Public Speaking" bahkan ketika kamu introvert
    8. Manfaat "Public Speaking"

**Comment by ridhof** [comment]
yang ditunggu2 nih 😂
