### ISSUE TITLE
Deteksi Objek dengan Opencv dan Python

### ISSUE THREAD

**Issue by HakimIhsan** [surabaya-py/talks#20]
*   Nama Lengkap: Fadl Lul Hakim Ihsan
*   Pekerjaan:  Mahasiswa
*   Kontak yang bisa dihubungi (Email/Telegram): t.me/Hakim_ihsan
*   Judul Lightning Talks: Vehicle Detector dengan Opencv dan Python
*   Overview (140 characters): Pada lightning talk ini saya ingin sharing tentang materi computer vision yakni cara mendeteksi objek menggunakan casecade classifier pada Opencv. Dalam hal ini objek yang dideteksi adalah kendaraan mobil.
*   Brief Outline: 
    1.  Review singkat computer vision untuk deteksi objek
    2.  Demo projek
    3.  Penjelasan singkat koding

**Comment by tegarimansyah** [comment]
Halo @HakimIhsan , materinya menarik banget. Mau ngisi untuk next meet up kah setelah bulan mei ini?

**Comment by HakimIhsan** [comment]
Wahh siap, insyaAllah.

**Comment by tegarimansyah** [comment]
Mantab! tunggu ya, nanti akan di follow up sama teman teman pengurus. Thank you.

**Comment by HakimIhsan** [comment]
:+1:
