### ISSUE TITLE
Penggunaan Python pada WebApps skala besar (odoo ERP WebApps)

### ISSUE THREAD

**Issue by EdyKend** [surabaya-py/talks#29]
*   Nama Lengkap: Edy Kend
*   Pekerjaan:  CEO
*   Kontak yang bisa dihubungi (Email/Telegram): paleleh@gmail.com
*   Judul Talks: Penggunaan Python pada WebApps skala besar (odoo ERP WebApps)
*   Overview (140 characters): 
odoo ERP merupakan erp opensource #1 (www.github.com/odoo) menggunakan python dengan skala besar dan luas, menggunakan lebih dari 40 library python seperti jinja2, babel, psycopg, werkzeug, greenlet, gevent
Odoo framework bisa menjadi referensi dan gudang ilmu dalam mempelajari dan pengembangan WebApps dengan Python
*   Brief Outline: 
    1.  Overview odoo
    2.  Python in odoo
    3.  Framework odoo
    4. Sistem Modular ala Python/odoo

**Comment by bimbimprasetyoafif** [comment]
Halo pak Edy

Topik nya menarik untuk dibawakan. Kira2 dari pak Edy butuh waktu berapa menit untuk full talk nya?

**Comment by bimbimprasetyoafif** [comment]
10 September 2022. Done and Thankyou pak Edy :)
