### ISSUE TITLE
Introduction to TPOT

### ISSUE THREAD

**Issue by rakhid16** [surabaya-py/talks#5]
*   Nama Lengkap: Radical Rakhman Wahid
*   Pekerjaan: Pelajar
*   Kontak yang bisa dihubungi (Email/Telegram): t.me/rakhmanWahid
*   Judul Lightning Talks: Automated Machine Learning in Python
*   Overview (140 characters): TPOT adalah modul dalam bahasa pemrograman Python yang berfungsi untuk mengoptimalkan/menentukan algoritma pembelajaran mesin secara otomatis dengan menggunakan algoritma genetika. Jadinya ya kalo kita punya dataset kita ndak perlu nyobain SEMUA algoritma dan ndak perlu juga coba-coba nyesuaiin parameternya buat cari tahu mana nih algoritma yang ngepas/cocok sama dataset kita.
*   Brief Outline: 
    1. Overview
    2. How it works
    3. Genetic algorithm
    4. How to start
    5. Choosing the best classifier and regressor
    6. End

**Comment by tegarimansyah** [comment]
Halo @Rakhid16 , Terima kasih sudah tertarik untuk mengisi Lightning Talks. Mohon bantuannya untuk mengedit judul dan overview. Judul digunakan untuk membuat orang yang membaca bisa tau tanpa harus klik ke issue tertentu. Overview digunakan untuk caption publikasi. Lagi pula, link github yang diberikan juga tidak bisa dibuka.

PS:
* Lightning talks memberikan kesempatan untuk pembicara berbagi ilmu secara garis besar selama kurang lebih 5 menit. Lebih dari itu panitia akan memberitau jika waktunya sudah habis.

**Comment by tegarimansyah** [comment]
Sip, thank you. Kita masukin di event 25 mei ini ya @Rakhid16
