### ISSUE TITLE
Using Pelican for Surabaya.py website, and how you can contribute

### ISSUE THREAD

**Issue by tegarimansyah** [surabaya-py/talks#7]
*   Nama Lengkap: Tegar Imansyah
*   Pekerjaan:  Research Engineer @ Alterra / Surabayapy Lead Organizer
*   Kontak yang bisa dihubungi (Email/Telegram): @tegarimansyah 
*   Judul Lightning Talks: Using Pelican for Surabaya.py website, and how you can contribute
*   Overview (140 characters): 

[Pelican](https://github.com/getpelican/pelican) merupakan sebuah static site generator, dan kami menggunakannya untuk membuat website [surabaya-py.github.io](surabaya-py.github.io). Disini akan sharing tentang bagaimana mudahnya menggunakan pelican dan cara kontribusi di website surabayapy.

*   Brief Outline: 
    1.  Konfigurasi awal pelican
    2. Kontribusi di surabayapy
    3. Pipeline dari source code menuju website yang live

**Comment by gallanpw** [comment]
Halo @tegarimansyah 

lanjutkan mas, meski aku belum tau pelican tapi ini bisa menambah ilmu baru juga, terus maju mas, asyiap hehehe
