### ISSUE TITLE
Smart Surveillance Video for Crime Prevention

### ISSUE THREAD

**Issue by dmaharika** [surabaya-py/talks#8]
*   Nama Lengkap: Dima Maharika Dinama
*   Pekerjaan:  Mahasiswa Teknik Mekatronika di Politeknik Elektronika Negeri Surabaya
*   Kontak yang bisa dihubungi (Email/Telegram): Telegram @dmdinama
*   Judul Lightning Talks: Smart Surveillance Video for Crime Prevention
*   Overview (140 characters): Saya ingin membicarakan SSV-Crive. Projek ini bertujuan untuk mendeteksi adanya pergerakan mencurigakan dalam rekaman video kamera pengawas. Hasil deteksi  kemudian akan memicu alarm untuk ditindaklanjuti oleh petugas keamanan.
*   Brief Outline: 
    1.  Brief History of Surveillance Video
    2.  Introduction to SSV-Crive
    3.  How it Works
    4.  Goals
    5.  Future Works
    6.  Conclusion

**Comment by tegarimansyah** [comment]
Halo @dmdinama 

Thank you sudah tertarik berkontribusi sebagai speaker lighning talk surabayapy. Untuk materi yang dibawakan sudah cukup, hanya karena kita punya timeframe 5 menit jadi mungkin bisa di optimalkan waktunya sehingga tidak terpotong di tengah pembahasan.

Hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.

**Comment by dmaharika** [comment]
Baik, @tegarimansyah

Terima kasih banyak atas kesempatannya. Saya akan berusaha semaksimal mungkin.
