### ISSUE TITLE
Integrating Django Drf With Elasticsearch using django elasticsearch dsl drf

### ISSUE THREAD

**Issue by Nazhier-Rijalana** [surabaya-py/talks#9]
*   Nama Lengkap: Nazhier Rijalana
*   Pekerjaan:  Backend Programmer at PT Jatim Indo Media (jatimnet.com)
*   Kontak yang bisa dihubungi (Email/Telegram): nazhier9974@gmail.com
*   Judul Lightning Talks: Integrating Django Drf with elasticsearch Using "django-elasticsearch-dsl-drf"
*   Overview (140 characters): Elasticsearch adalah sebuah tools yang digunakan untuk melakukan indexing data/document dari mysql ke document dalam bentuk json, saya ingin mengshare bagaimana cara mengintegrasikannya dengan django rest framework
*   Brief Outline: 
    1.  Introduction of elasticsearch
    2.  Purpose Of Django-Elasticsearch-Dsl-DRF 
    3.  How to Integrated to Django Rest Framework
    4.  Conclusion

**Comment by alifakbar111** [comment]
hallo @Nazhier-Rijalana 

Terima kasih sudah tertarik untuk mengisi Lightning Talks. Dikarenakan keterbatasan waktu yang hanya 5 menit kami sarankan untuk bagian Brief Outline bisa di kurangi dan langsung pada inti penggunakan Django Elasticsearch.

Terima Kasih

**Comment by Nazhier-Rijalana** [comment]
> hallo @Nazhier-Rijalana
> 
> Terima kasih sudah tertarik untuk mengisi Lightning Talks. Dikarenakan keterbatasan waktu yang hanya 5 menit kami sarankan untuk bagian Brief Outline bisa di kurangi dan langsung pada inti penggunakan Django Elasticsearch.
> 
> Terima Kasih

sudah saya edit kakak terima kasih atas masukannya

**Comment by tegarimansyah** [comment]
Halo @Nazhier-Rijalana 

Terima kasih sudah di update untuk brief outlinenya. Materinya sangat menarik, ditunggu di meet up nanti.

Hari ini kami akan coba kirimkan surat undangan dan speaker guide. Semoga bisa membantu untuk membuat slide yang ramping namun padat.

Have a good day.
